services:
  app:
    image: sogisurvey
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db:db
    environment:
      PORT: 8080
      JDBC_DATABASE_URL: jdbc:postgresql://db/?user=postgres&password=postgres&ssl=false&port=5432
    command: ./wait-for-it.sh -t 40 db:5432 -- java -jar /app/sogisurvey.jar
  db:
    image: postgres:13.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sogisurvey
